# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    stdlib: 
      repo: "puppetlabs/stdlib" # needs stdlib 9 >
      ref: "9.6.0"
    puppetlabs-yumrepo_core:
      repo: "puppetlabs/yumrepo_core"
      ref: "2.1.0"
    puppet-archive:
      repo: "puppet/archive"
      ref: "7.1.0"
    puppetlabs-mysql:
      repo: "puppetlabs/mysql" # needs 15 or > 
      ref: "15.0.0"
    puppetlabs-cron_core:
      repo: "puppetlabs/cron_core"
      ref: "1.3.0"
    puppet-selinux:
      repo: "puppet/selinux" # needs stdlib 9 > 
      ref: "4.1.0" # needs 4>
    puppetlabs-apache:
      repo: "puppetlabs/apache"
      ref: "12.0.3"
    puppet-snmp:
      repo: "puppet/snmp" # needs systemd 2.5.1 >
      ref: "7.1.0"
    puppet-firewalld:
      repo: "puppet/firewalld"
      ref: "5.0.0"
    domkrm-ufw: # consider moving to another modules for ufw
      repo: "domkrm/ufw"
      ref: "1.1.4"
    puppet-systemd: # inifile is dep
      repo: "puppet/systemd"
      ref: "7.0.0"
    puppetlabs-concat: # needs stdlib 9 > 
      repo: "puppetlabs/concat"
      ref: "9.0.2"
    puppetlabs-augeas_core:
      repo: "puppetlabs/augeas_core"
      ref: "1.5.0"
  repositories:
    provision: https://github.com/puppetlabs/provision.git
    puppet_agent:
      repo: https://github.com/puppetlabs/puppetlabs-puppet_agent.git
      ref: v4.19.0
    facts: https://github.com/puppetlabs/puppetlabs-facts.git