# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    stdlib: 
      repo: "puppetlabs/stdlib"
      ref: "8.6.0"
    puppetlabs-yumrepo_core:
      repo: "puppetlabs/yumrepo_core"
      ref: "1.0.7"
    puppet-archive:
      repo: "puppet/archive"
      ref: "5.0.0"
    puppetlabs-mysql:
      repo: "puppetlabs/mysql"
      ref: "13.3.0"
    puppetlabs-cron_core:
      repo: "puppetlabs/cron_core"
      ref: "1.0.5"
    puppet-selinux:
      repo: "puppet/selinux"
      ref: "3.4.0"
    puppetlabs-apache:
      repo: "puppetlabs/apache"
      ref: "10.0.0"
    puppet-snmp:
      repo: "puppet/snmp"
      ref: "5.1.1"
    puppet-firewalld:
      repo: "puppet/firewalld"
      ref: "4.4.0"
    domkrm-ufw:
      repo: "domkrm/ufw"
      ref: "1.1.4"
    camptocamp-systemd:
      repo: "camptocamp/systemd"
      ref: "3.0.0"
    puppetlabs-concat:
      repo: "puppetlabs/concat"
      ref: "7.0.1"
    puppetlabs-augeas_core:
      repo: "puppetlabs/augeas_core"
      ref: "1.1.2"