---
name: "Acceptance Testing"

on: 
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "main"

jobs:

  setup_matrix:
    name: "Setup Test Matrix"
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.get-matrix.outputs.matrix }}

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
      if: ${{ github.repository_owner == 'benjamin-robertson' }}

    - name: Activate Ruby 3.2
      uses: ruby/setup-ruby@v1
      if: ${{ github.repository_owner == 'benjamin-robertson' }}
      with:
        ruby-version: "3.2.3"
        bundler-cache: true

    - name: Print bundle environment
      if: ${{ github.repository_owner == 'benjamin-robertson' }}
      run: |
        echo ::group::bundler environment
        bundle env
        echo ::endgroup::

    - name: Setup Integration Test Matrix
      id: get-matrix
      run: |
        echo  "matrix={'platform':['centos-stream8'],'collection':['puppet7', 'puppet8'],'gem_version':['~> 7.31', '~> 8.7']}" >> $GITHUB_OUTPUT

  acceptance:
    name: "Acceptance tests (${{matrix.platform}}, ${{matrix.collection}})"
    needs:
      - setup_matrix
    if: ${{ needs.setup_matrix.outputs.matrix != '{}' }}

    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.setup_matrix.outputs.matrix)}}

    env:
      PUPPET_GEM_VERSION: ${{matrix.gem_version}}
      FACTER_GEM_VERSION: 'https://github.com/puppetlabs/facter#main'  # why is this set?

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3

    - name: Activate Ruby 3.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.2.3"
        bundler-cache: true

    - name: Print bundle environment
      run: |
        echo ::group::bundler environment
        bundle env
        echo ::endgroup::

    - name: Create the fixtures directory
      run: |
        bundle exec rake spec_prep

    - name: check vars
      run: |
        export

    - name: Provision test environment
      run: |
        bundle exec rake 'litmus:provision_list[docker]'
        FILE='spec/fixtures/litmus_inventory.yaml'

    - name: Install Agents and module
      run: |
        # bundle exec rake 'litmus:install_agent'
        bundle exec rake 'litmus:install_agent[${{ matrix.collection }}]'
        bundle exec rake litmus:install_module

    - name: Run integration tests
      run: |
        bundle exec rake litmus:acceptance:parallel

    - name: Remove test environment
      if: ${{ always() }}
      continue-on-error: true
      run: |
        ls -lh ./spec/fixtures/
        cat ./spec/fixtures/litmus_inventory.yaml
        bundle exec rake 'litmus:tear_down'