---
name: "Integration Testing"

on: 
  push:
    branches:
      - "*"

jobs:

  setup_matrix:
    name: "Setup Test Matrix"
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.get-matrix.outputs.matrix }}

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
      if: ${{ github.repository_owner == 'benjamin-robertson' }}

    - name: Activate Ruby 2.7
      uses: ruby/setup-ruby@v1
      if: ${{ github.repository_owner == 'benjamin-robertson' }}
      with:
        ruby-version: "2.7"
        bundler-cache: true

    - name: Print bundle environment
      if: ${{ github.repository_owner == 'benjamin-robertson' }}
      run: |
        echo ::group::bundler environment
        bundle env
        echo ::endgroup::

    - name: Setup Integration Test Matrix
      id: get-matrix
      run: |
        if [ '${{ github.repository_owner }}' == 'benjamin-robertson' ]; then
          echo  "matrix={'platform':['centos-stream8'],'collection':['puppet7-nightly', 'puppet8-nightly']}" >> $GITHUB_OUTPUT
        else
          echo  "matrix={}"  >> $GITHUB_OUTPUT
        fi

  Integration:
    needs:
      - setup_matrix
    if: ${{ needs.setup_matrix.outputs.matrix != '{}' }}

    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.setup_matrix.outputs.matrix)}}

    env:
      PUPPET_GEM_VERSION: '~> 7.24'
      FACTER_GEM_VERSION: 'https://github.com/puppetlabs/facter#main'  # why is this set?

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3

    - name: Activate Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "2.7"
        bundler-cache: true

    - name: Print bundle environment
      run: |
        echo ::group::bundler environment
        bundle env
        echo ::endgroup::

    - name: Create the fixtures directory
      run: |
        bundle exec rake spec_prep

    - name: check vars
      run: |
        export

    - name: Provision test environment
      run: |
        bundle exec bolt --modulepath spec/fixtures/modules plan run observium::acceptance::provision_integration image=${{ matrix.platform }}
        # Redact password
        FILE='spec/fixtures/litmus_inventory.yaml'
        sed -e 's/password: .*/password: "[redacted]"/' < $FILE || true

    - name: Install Agents
      run: |
        bundle exec rake 'litmus:install_agent'

    - name: Run integration tests
      run: |
        bundle exec rake observium:integration

    - name: Remove test environment
      if: ${{ always() }}
      continue-on-error: true
      run: |
        bundle exec rake 'litmus:tear_down'